### ISSUE TITLE
Checklist da Base

### ISSUE THREAD

**Issue by nycholassousa** [nycholassousa/TibianosCustom#1]
Inicial: 
- [ ] Usar distro com base no OTX global: source e modules
- [ ] Usar datapack base do TFS

Imbuement:
- [ ] Testar IDs
- [ ] Testar movements
- [ ] Testar spell com elemento de arma baseado

Prey Sytem:
- [ ] Testar bonus
- [ ] Testar rerolls

Reward System:
- [ ] Testar loot dos bosses

Critical/Leech:
- [ ] Funcionalidade
